on:
  push:
name: example
jobs:
  lint:
    name: run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: run lint command
        run: npm run lint
  test:
    name: run test
    runs-on: ubuntu-latest
    env:
      TEST_DB_USERNAME: ieqovpfr
      TEST_DB_PASSWORD: SMTvmfONN73gNGHjmwNvBBF1sAMALoyx
      TEST_DB_DATABASE: ieqovpfr
      TEST_DB_NAME: ieqovpfr
      TEST_DB_HOST: flora.db.elephantsql.com
      TEST_DB_PORT: 5432
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: run test command
        run: npm run test
#https://docs:github:com/en/actions/using-containerized-services/creating-postgresql-service-containers
